### ISSUE TITLE
unable to find version `latest`

### ISSUE THREAD

**Issue by mittalyashu** [rome/setup-rome#15]
Using this action throw in error.

`Error: Unable to resolve action "rome/setup-rome@latest", unable to find version "latest"`

Using it like this

```yml
- name: Install Rome
  uses: rome/setup-rome@latest
  with:
    version: latest
```

**Comment by mittalyashu** [comment]
Actually there might be an issue in the README.md file. By changing the version like this it worked:

```
- name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: latest
```

I think `@latest` syntax is not supported in GitHub Actions _(couldn't find anything related even in GitHub help docs)_.
