### ISSUE TITLE
bug: Unable to install when setting specific version

### ISSUE THREAD

**Issue by elijaholmos** [rome/setup-rome#16]
I encountered an error when running the action from the following configuration: 

```yml
name: Code Style
on:
  pull_request:
    branches: [main]
    paths: ['**.js', '**.ts']

jobs:
  rome-ci:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: 10.0.1

      - name: Check Rome Version
        run: rome version

      - name: Run Linter & Formatter
        run: rome ci .
```

![image](https://user-images.githubusercontent.com/35435704/205420508-8562eb01-dbed-4312-a6d2-1dfc2c251186.png)

I intend on submitting a PR to resolve this issue.
